[env]
GOEXPERIMENT = 'jsonv2'
AWS_ACCESS_KEY_ID = 'user'
AWS_SECRET_ACCESS_KEY = 'password'

[tasks.fmt]
run = 'go fmt ./...'

[tasks.container-start]
run = [
    "docker compose up -d"
]

[tasks.run-worker]
run = 'go run main.go receiverWorker'
description = 'Build the app'

[tasks.run-provider]
run = 'go run main.go providerApi'
description = 'Build the app'
