CREATE TABLE IF NOT EXISTS `houry_api_usage` (
    `account_id` bigint UNSIGNED NOT NULL DEFAULT 0,
    `hour` VARCHAR(10) NOT NULL, -- 2024010215
    `usage` bigint UNSIGNED NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (`account_id`, `hour`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
