CREATE TABLE IF NOT EXISTS `account` (
    `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
    `account_name` VARCHAR(255) NOT NULL,
    `timezone` VARCHAR(20),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
